"""create anomalies table

Revision ID: 16c7fee4a671
Revises: 1bfffe9c0723
Create Date: 2026-04-23 16:26:10.231089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c7fee4a671'
down_revision: Union[str, Sequence[str], None] = '1bfffe9c0723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_pk', sa.Integer(), nullable=False),
    sa.Column('latest_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_pk'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_created_at'), 'anomalies', ['created_at'], unique=False)
    op.create_index(op.f('ix_anomalies_latest_snapshot_id'), 'anomalies', ['latest_snapshot_id'], unique=False)
    op.create_index(op.f('ix_anomalies_market_pk'), 'anomalies', ['market_pk'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.alter_column('markets', 'market_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('markets', 'event_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('markets', 'ticker',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('markets', 'ticker',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('markets', 'event_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('markets', 'market_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_market_pk'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_latest_snapshot_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_created_at'), table_name='anomalies')
    op.drop_table('anomalies')
    # ### end Alembic commands ###
