"""create markets table

Revision ID: 37a3e393184b
Revises: 
Create Date: 2026-04-23 15:00:55.737185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a3e393184b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('ticker', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_event_id'), 'markets', ['event_id'], unique=False)
    op.create_index(op.f('ix_markets_market_id'), 'markets', ['market_id'], unique=True)
    op.create_index(op.f('ix_markets_platform'), 'markets', ['platform'], unique=False)
    op.create_index(op.f('ix_markets_ticker'), 'markets', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_ticker'), table_name='markets')
    op.drop_index(op.f('ix_markets_platform'), table_name='markets')
    op.drop_index(op.f('ix_markets_market_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_event_id'), table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
