"""create market snapshots table

Revision ID: a75e4b985b38
Revises: 37a3e393184b
Create Date: 2026-04-23 15:17:45.378372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75e4b985b38'
down_revision: Union[str, Sequence[str], None] = '37a3e393184b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_pk', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_price_dollars', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('yes_bid_dollars', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('yes_ask_dollars', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('no_bid_dollars', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('no_ask_dollars', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume_fp', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('volume_24h_fp', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('open_interest_fp', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('liquidity_dollars', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['market_pk'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_market_pk'), 'market_snapshots', ['market_pk'], unique=False)
    op.create_index(op.f('ix_market_snapshots_ts'), 'market_snapshots', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_snapshots_ts'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_market_pk'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    # ### end Alembic commands ###
