"""create anomalies table

Revision ID: da2173380c55
Revises: 16c7fee4a671
Create Date: 2026-04-23 16:32:30.808663

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'da2173380c55'
down_revision: Union[str, Sequence[str], None] = '16c7fee4a671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
